[package]
name = "arp-toolkit"
version = "0.1.0"
authors = ["Oliver Layer <olilay@live.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
num-traits = "0.2"
num-derive = "0.3"